wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.0
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681979059.83167
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.7.16
      5: 0.15.0
      8:
      - 5
